---
title: 'IO Assignment #3'
author: "Vladimir Smiljanic & Juan David Rios"
date: '2017-03-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

We can define the mean utility for product j at time t that all consumers receive:
\begin{align*}
\delta_{jt} = x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt}
\end{align*}
Where $u_{ijt} = \delta_{jt}(x_{jt}, p_{jt},m_j,\xi;\beta,\alpha) + \lambda c_t + \epsilon_{ijt}$.

From Berry (1994) we know that the variation in consumer tastes only enters through the error term $\epsilon_{ijt}$ which is assumed to be iid extreme value or logit distribution across all consumers and choices. 
\begin{align*}
F(\delta_{0t}\dots\delta_{Jt}) = \exp(-\exp(-I))\\
\end{align*}
Where $I$ is inclusive value $\ln \sum^J_{k=0}\exp(\delta_k)$. We can interpret $I$ as the expected value of the maximum over all utilities.

As a result, all properties of market demand are determined by $\delta_{jt}$, which includes market shares and elasticities. As a result, cross-price elasticities only depend on $\delta_{jt}$ with no additional effect from product charasteristics and prices. Errors that are iid results in two pairs of goods (ie. cars) with the same market shares will have the same cross-price elasticity with a third good.

Individuals choose the product out of the total products available plus the outside good. The probability that individual i chooses product j takes the following form:
\begin{align*}
s_{jt} &= \frac{\exp(\delta_{j})}{\exp{I}}\\
s_{jt} &= \frac{\exp(x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt})}{1 + \sum^{J}_{k=1} \exp(\delta_{kt})}\\
\end{align*}
We also know the probability that an individual chooses the outside good which is given by. This is due to the fact that we normalize the mean utility that any idividual gets from the outside good to be equal to 0. 
\begin{align*}
s_{0t} &= \frac{\exp(\delta_0)}{\exp(I)}\\ 
s_{0t} &= \frac{1}{1 + \sum^{J}_{k=1} \exp(\delta_{kt})}
\end{align*}
After defining $s_{0t}$ and $s_{jt}$ we can now perform a Berry inversion as seen in Berry (1994). 

\begin{align*}
\frac{s_{jt}}{s_{0t}} &=  \frac{\frac{\exp(x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt})}{1 + \sum^{J}_{k=1} \exp(\delta_{kt})}}{\frac{1}{1 + \sum^{J}_{k=1} \exp(\delta_{kt})}}  \\
\frac{s_{jt}}{s_{0t}} &= \exp(x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt})\\
\ln(\frac{s_{jt}}{s_{0t}}) &= \ln(\exp(x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt}))\\
\ln(\frac{s_{jt}}{s_{0t}}) &= x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt}
\end{align*}

This is the specification that will be taken to the data using OLS and 2SLS.

2. *Discuss the endogeneity problem and how you are going to treat it. You can use the observed nonprice attributes as instruments under the assumption that they are exogeneous as in BLP(1995). You can use the sums and the count of characteristics by country and year , and by country year and firm.*

The endogeneity problem exists in that there is strong argument to be made that $\xi$ the econometric error term that contains all unobserved characteristics for product j is correlated with price. Thus $E[\xi | X]= 0$. For example one could assume an unobserved characteristic could be the prestige associated with a brand. It would be reasonable to assume that a consumer would get more utility and be willing to pay more for a high prestige brand such as ferrari in comparison to a less prestigious car even holding observed characteristics constant.

To combat this resulting bias we will be using the sum of the characteristics of the all the cars made by firms other that the firm that produces the good, as well as the sum of characteristics of all other makes of the firm that produces the car. The reasoning brovide by Berry (1995) is that since the utility one gets from purchasing a car is uncorrelated with the characteristics of non-purchased cars but competitors must price based on their competition the sum of the characteristics of all other cars follows these properties $E[P|Z] \ne 0$ and $E[\xi|z]= 0$. Thus the sum of other car characteristics are valid instruments if the previous assumptions hold. 

3. *Algebraically derive the own price and cross price elasticities in the logit model ( Show all steps)*

For ease of computation define $M_j \equiv \exp(x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt})$

Crossprice Elasticity:

\begin{align*}
s_{jt} &= \frac{\exp(\delta_{jt})}{1 + \sum^{J}_{k=1} \exp(\delta_{kt})} \\
s_{jt} &= \frac{M_j}{1 + \sum^{J}_{k=1} M_k} \\
\frac{\partial M_j}{\partial p_{kt}} &= 0\\
\frac{\partial s_{jt}}{\partial p_{kt}} &= \frac{\frac{\partial M_j}{\partial p_{kt}}}{1 + \sum^{J}_{k=1} M_k} + \frac{-M_j}{(1 +\sum^{J}_{k=1} M_k)^2} \times \frac{\partial M_k}{\partial p_{kt}} \\
\frac{\partial s_{jt}}{\partial p_{kt}} &= \frac{0}{1 + \sum^{J}_{k=1} M_k} + \frac{-M_j}{(1 +\sum^{J}_{k=1} M_k)^2} \times (-\alpha M_k)\\
\frac{\partial s_{jt}}{\partial p_{kt}} &= \alpha \times \frac{M_j}{1 +\sum^{J}_{k=1} M_k} \times \frac{M_k}{1 + \sum^{J}_{k=1} M_k}\\
\frac{\partial s_{jt}}{\partial p_{kt}} &= \alpha s_{jt}s_{kt}\\
\end{align*}

We can now use this to find our crossprice elasticity:
\begin{align*}
\frac{\partial q_k}{\partial p_j}\frac{p_j}{q_k} &= \frac{L\partial s_k}{\partial p_j}\frac{p_j}{q_k}\\
&= L (\alpha s_{j}s_{k})\frac{p_j}{q_k}\\
&= L (\alpha s_{j}\frac{q_k}{L})\frac{p_j}{q_k}\\
&= \alpha s_j p_j\\
\end{align*}


for own price elasticity and k = j : 
\begin{align*}
\frac{\partial s_{jt}}{\partial p_{jt}} &= \frac{\frac{\partial M_j}{\partial p_{jt}}}{1 + \sum^{J}_{k=1} M_k} + \frac{-M_j}{(1 + \sum^{J}_{k=1} M_k)^2} \times \frac{\partial M_j}{\partial p_{jt}} \\
\frac{\partial s_{jt}}{\partial p_{jt}} &= \frac{-\alpha M_j}{1 + \sum^{J}_{k=1} M_j} + \frac{-M_j}{( 1 + \sum^{J}_{k=1} M_k)^2} \times (-\alpha M_j)\\
\frac{\partial s_{jt}}{\partial p_{jt}} &=  - \alpha s_{jt}  + \alpha s^2_{jt}\\
\frac{\partial s_{jt}}{\partial p_{jt}} &=  - \alpha s_{jt}(1 - s_{jt})\\
\end{align*}

We can use similar procedure to solve for own price elasticity:

\begin{align*}
\frac{\partial q_j}{\partial p_j}\frac{p_j}{q_k} &= \frac{L\partial s_j}{\partial p_j}\frac{p_j}{q_j}\\
&= L (- \alpha s_{j}(1 - s_{j})\frac{p_j}{q_j}\\
&= L (-\alpha s_{j}\frac{q_j}{L})(1 - s_{j})\frac{p_j}{q_j}\\
&= -\alpha p_j(1-s_j)\\
\end{align*}

4. *Estimate the logit using OLS and 2SLS with car model fixed effects, using the instruments discussed above. Report the coefficients and the standard errors for the product characteristics and price. How does the coefficient of price change when you use instruments?*. 

Estimating logit using OLS and 2SLS with car model fixed effects as well as instruments. 

```{}
egen yearcountry=group(year country), label
xtset co yearcountry

// Defining outside good as MSIZE

gen MSIZE=pop/4

#delimit ;

local characteristics "horsepower fuel width height domestic";

* Sum of the characteristics of all competing products and competing products produced by other firms;

foreach inst in `characteristics'{;
qui{;
	egen i_`inst'=sum(`inst'), by (year country);
	egen if_`inst'=sum(`inst'), by (year country firm);
	gen CFi_`inst'=i_`inst'-if_`inst';
	replace i_`inst'=i_`inst'-`inst';
	replace if_`inst'=if_`inst'-`inst';
};
};

qui egen tot_sales=sum(qu), by(year country);
qui egen i_num=count(qu), by(year country);

qui egen firm_sales=sum(qu), by(year country firm);
qui egen if_num=count(qu), by(year country firm);

qui gen CFi_num=i_num-if_num;

replace i_num=i_num-1;
gen lni_num=ln(i_num);

replace if_num=if_num-1;
gen lnif_num=ln(if_num);

gen rewr=ln(qu/(MSIZE-tot_sales));

xtreg rewr price horsepower fuel width height domestic year country2-country5, fe;

xtivreg rewr (price = 	i_horsepower i_fuel i_width i_height i_domestic i_num
							if_horsepower if_fuel if_width if_height if_domestic i_num)
							horsepower fuel width height domestic year country2-country5, fe;
	
```

*Coefficients and standard errors for product charactersitics and price*

```{}

xtreg rewr price horsepower fuel width height domestic year country2-country5, fe;

Fixed-effects (within) regression               Number of obs      =     11483
Group variable: co                              Number of groups   =       351

R-sq:  within  = 0.4439                         Obs per group: min =         1
       between = 0.1552                                        avg =      32.7
       overall = 0.3471                                        max =       146

                                                F(11,11121)        =    807.15
corr(u_i, Xb)  = -0.0355                        Prob > F           =    0.0000

------------------------------------------------------------------------------
        rewr |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       price |   -.050574   .0029855   -16.94   0.000    -.0564261   -.0447218
  horsepower |  -.0105318   .0013525    -7.79   0.000     -.013183   -.0078807
        fuel |  -.0555518   .0104271    -5.33   0.000    -.0759907   -.0351128
       width |   .0618035   .0038153    16.20   0.000     .0543248    .0692822
      height |   .0301939   .0050837     5.94   0.000     .0202289    .0401588
    domestic |   1.852258   .0225663    82.08   0.000     1.808024    1.896492
        year |  -.0448788   .0027147   -16.53   0.000    -.0502001   -.0395575
    country2 |  -.9618966   .0250186   -38.45   0.000    -1.010937   -.9128558
    country3 |  -.8360231   .0250937   -33.32   0.000    -.8852112    -.786835
    country4 |  -.7841082   .0268119   -29.24   0.000    -.8366642   -.7315522
    country5 |  -.5148567   .0337275   -15.27   0.000    -.5809687   -.4487448
       _cons |    69.6166   5.087516    13.68   0.000     59.64416    79.58903
-------------+----------------------------------------------------------------
     sigma_u |  1.0115597
     sigma_e |  .83600972
         rho |  .59416655   (fraction of variance due to u_i)
------------------------------------------------------------------------------
F test that all u_i=0:     F(350, 11121) =    28.23          Prob > F = 0.0000

xtivreg rewr (price =   i_horsepower i_fuel i_width i_height i_domestic i_num
>                       if_horsepower if_fuel if_width if_height if_domestic i_num)
>                       horsepower fuel width height domestic year country2-country5, fe;

note: i_num omitted because of collinearity

Fixed-effects (within) IV regression         Number of obs      =        11483
Group variable: co                           Number of groups   =          351

R-sq:  within  = 0.4299                      Obs per group: min =            1
       between = 0.1897                                     avg =         32.7
       overall = 0.3501                                     max =          146

                                             Wald chi2(11)      =    848625.94
corr(u_i, Xb)  = -0.0999                     Prob > chi2        =       0.0000

------------------------------------------------------------------------------
        rewr |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       price |  -.1005664   .0177525    -5.66   0.000    -.1353608   -.0657721
  horsepower |  -.0025321   .0031163    -0.81   0.416    -.0086399    .0035757
        fuel |  -.0595718    .010651    -5.59   0.000    -.0804474   -.0386962
       width |   .0656646   .0040925    16.04   0.000     .0576433    .0736858
      height |   .0318221   .0051788     6.14   0.000     .0216718    .0419724
    domestic |   1.834104   .0237157    77.34   0.000     1.787622    1.880586
        year |   -.054858    .004444   -12.34   0.000     -.063568    -.046148
    country2 |  -.9278147   .0279989   -33.14   0.000    -.9826915   -.8729379
    country3 |  -.8877051   .0311868   -28.46   0.000    -.9488302     -.82658
    country4 |  -.6695734   .0484069   -13.83   0.000    -.7644492   -.5746975
    country5 |  -.1332703   .1378219    -0.97   0.334    -.4033964    .1368557
       _cons |   88.97039   8.508741    10.46   0.000     72.29356    105.6472
-------------+----------------------------------------------------------------
     sigma_u |  1.0364758
     sigma_e |  .84648344
         rho |  .59988403   (fraction of variance due to u_i)
------------------------------------------------------------------------------
F  test that all u_i=0:     F(350,11121) =    26.70       Prob > F    = 0.0000
------------------------------------------------------------------------------
Instrumented:   price
Instruments:    horsepower fuel width height domestic year country2 country3
                country4 country5 i_horsepower i_fuel i_width i_height
                i_domestic i_num if_horsepower if_fuel if_width if_height
                if_domestic
------------------------------------------------------------------------------

```


We can see that the coefficient on price decreases as we include instruments. The Instrumented coefficient on price  -.1005664 is larger in absolute value to the  
coefficient calculated with out instruments -.050574. This confirms the suspicion that the non-instrumented results were biased downwards and it was nessecary to use the following instruments.  

5. *Calculate the elasticities and report summary statistics*.

From our summary table for coefficients and standards errors, we see that our coefficient on prices for logit model with instrumental variables is $\alpha=0.1005664$. The regression notes that this coefficient is negative but our model setup the regression to have a negative sign in front of $\alpha$. Hence $\alpha$ itself is positive. We can input that value into our price elasticity equation and summarize the results.

*Own price elasticities*
```{}
gen alp = 0.1005664;
gen sj = qu/MSIZE;
gen oel=1alp*price*(1-sj);

sum oel;

    Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
         oel |     11483   -1.857588    .8975175  -15.11824  -.5274911

```

*Cross-price elasticities*
```{}
gen cel = alp*price*sj;

sum cel;

    Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
         cel |     11483    .0025719    .0038055   .0000141    .035288

```

## Question 2

1. Deriving Berry-one-level nested logit begining from the utility following utility specification. 

\begin{align*}
u_{ijt} = \delta_{jt}(x_{jt}, p_{jt},m_j,\xi;\beta,\alpha) + \lambda c_t + \epsilon_{ijt}
\end{align*}

We than divide the products into mutually exclusive nests which we note by $g = 0 \dots G$ where $g=0$ is the nest that only contains the outside good. In this case the products will be divided based on market segment, such as (compact, luxury , intermediate ... and a nest for the outside good). 

In the nested logiot the individual error term $\epsilon_{ijt}$ is composed of two parts
\begin{align*}
\epsilon_{ijt} = (1-\sigma_g)\epsilon{igt} + \epsilon_{ijt}^1
\end{align*}

The first term $\epsilon_{igt}$ is an error shared by all products in nest g. The second term $\epsilon_{ijt}^1$ is an i.i.d extreme value shock similar to the one seen in the logit in question 1. The term $(1-\sigma_g)$ denotes how important the within nest shock in comparison to the extreme value shock.  $\epsilon{igt}$ has the property that it is distributed in such a manner that it makes the whole term $(1-\sigma_g)\epsilon{igt} + \epsilon_{ijt}^1$ also type one extreme value distributed. Since we assume that heterogeneity across clusters we can assume that $\sigma_g = \sigma \textrm{ for all } g$. 

Since $\epsilon_{ijt}$ is extreme value distributed $F(\delta_{0t}\dots\delta_{Jt}) = \exp(-\exp(-I))$. 

Following the same notation as Berry 1994: 
\begin{align*}
D_g &= \sum^{J_g}_{j=1}\exp(\delta_j/(1-\sigma_g)))\\
I_g&=(1-\sigma_g)\ln(D_g)\\
I&=\ln(\sum^G_{g=0}D^{(1-\sigma_g)}_g)\\  
\end{align*}

Our market share equations become
\begin{align*}
s_{j} &= \frac{\exp(\delta_{j}/(1-\sigma_g))\exp((1-\sigma_g)\ln(D_g))}{(D_g)(\sum^G_{g=0}D^{(1-\sigma_g)}_g)} \\
s_{j} &= \frac{\exp(\delta_{j}/(1-\sigma_g))}{D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g}\\
s_{0} &= \frac{1}{\sum^G_{g=0}D^{(1-\sigma_g)}_g}
\end{align*}

\begin{align*}
\ln(s_{j}) &= \frac{\exp(\delta_{j}/(1-\sigma_g))}{D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g}) \\
\ln(s_{j}) &= \frac{\delta_{j}}{(1-\sigma_g)}  - \ln(D_g^\sigma)-ln(\sum^G_{g=0}D^{(1-\sigma_g)}_g)
\end{align*}

\begin{align*}
\ln(s_0) &= \ln(\frac{1}{\sum^G_{g=0}D^{(1-\sigma)}_g}) \\
\ln(s_0) &= -\ln(\sum^G_{g=0}D^{(1-\sigma)}_g) 
\end{align*}

\begin{align*}
\ln(s_{j}) - \ln(s_0) &= \frac{\delta_{j}}{(1-\sigma)}  - \ln(D_g^\sigma)-ln(\sum^G_{g=0}D^{(1-\sigma)}_g) +\ln(\sum^G_{g=0}D^{(1-\sigma)}_g) \\
\ln(\frac{s_{j}}{s_0}) &= \frac{\delta_{j}}{(1-\sigma)}  - \sigma \ln(D_g) \\
\end{align*}

The market share of a certain segment g, $s_g =\frac{D_g^{(1-\sigma_g)}}{\sum^G_{g=0}D^{(1-\sigma_g)}_g}$ taking the log of both sides. 

\begin{align*}
\ln(s_g) &= \ln(\frac{D_g^{(1-\sigma_g)}}{\sum^G_{g=0}D^{(1-\sigma_g)}_g})\\
\ln(s_g) &= (1-\sigma) \ln(D_g) - \ln(s_0)\\
\ln(D_g) &= \frac{\ln(s_g) - \ln(s_0)}{1-\sigma}
\end{align*}

Defining $s_{j|g} = \frac{s_j}{s_k}$ and subsituting expression for $\ln(D_g)$ into $\ln(\frac{s_{j}}{s_0})$

\begin{align*}
\ln(\frac{s_{j}}{s_0}) &= \frac{\delta_{j}}{(1-\sigma)}  - \sigma \ln(D_g) \\
\ln(\frac{s_{j}}{s_0}) &= \frac{\delta_{j}}{(1-\sigma)}  - \sigma \frac{\ln(s_g) - \ln(s_0)}{1-\sigma} \\
(\ln(s_j) - \ln(s_0))(1-\sigma) &= \delta_{j} -\sigma (\ln(s_g) - \ln(s_0))\\
\ln(s_j) - \ln(s_0) -\ln(s_j)\sigma  + \ln(s_0) \sigma + \sigma \ln(s_g)  + \sigma \ln(s_0) = \delta_{j} \\
\ln(\frac{s_{j}}{s_0}) -\sigma \ln(s_{j|g}) &= \delta_{j} \\
\ln(\frac{s_{j}}{s_0}) &= \delta_{j} +\sigma \ln(s_{j|g}) \\
 \ln(\frac{s_{j}}{s_0})  &= x_{jt}\beta - \alpha p_{jt} + \gamma m_j + \xi_{jt}  +\sigma \ln(s_{j|g})
\end{align*}

This is the specification for a Berry-one-level nested logit which we will estimate using OLS and 2SLS. 
 
2. Discuss Endogeneity problem and how you will treat it. 

We continue to have an endogeinty problem with prices being correlated with our unobserved characteristics contained in the econometric error similar to Q1.2  In addition the term $\ln(s_{j|g})$ creates additional endogeneity problems. It tends to reason that some of the unobserved characteristics will lead to a higher share within the segment. One such example is if a compact car has a reputation for being reliable, we do not have a varaible to identify this but it stands to reason that this product would capture a larger share of the compact car segment. For this reason we need two instruments one for price and one for  $\ln(s_{j|g})$. Once again we will relly on whithin firm other product characteristics as well as outside of firm other product characteristics and additionally within segment other product characteristics. 


3.
\begin{align*}
s_{j} &= \frac{\exp(\delta_{j}/(1-\sigma_g))\exp(I_g)}{\exp(I_g/(1-\sigma_g))\exp(I)} \\
I&=\ln(\sum^G_{g=0}\exp(I_g))\\  
I_g&=(1-\sigma_g)\ln(\sum^{J_g}_{j=1}\exp(\delta_j/(1-\sigma_g)))\\
\end{align*}

Using notation from Barry's paper, we can simplify summations by:

\begin{align*}
D_g &= \sum^{J_g}_{j=1}\exp(\delta_j/(1-\sigma_g)))\\
I_g&=(1-\sigma_g)\ln(D_g)\\
I&=\ln(\sum^G_{g=0}D^{(1-\sigma_g)}_g)\\  
\end{align*}

As a result, we can simplify our product shares formula:

\begin{align*}
s_{j} &= \frac{\exp(\delta_{j}/(1-\sigma_g))\exp((1-\sigma_g)\ln(D_g))}{(D_g)(\sum^G_{g=0}D^{(1-\sigma_g)}_g)} \\
s_{j} &= \frac{\exp(\delta_{j}/(1-\sigma_g))}{D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g} \\
\end{align*}

We can also lay out the equation for shares of outside good:

\begin{align*}
s_{0} &= \frac{1}{\sum^G_{g=0}D^{(1-\sigma_g)}_g} \\
\end{align*}

We determine our price elasticities, we need to know the probability of choosing one of the group g products:

\begin{align*}
s_g&=\frac{D_g^{(1-\sigma_g)}}{\sum^G_{g=0}D^{(1-\sigma_g)}_g}\\
s_{j|g} &= \frac{s_j}{s_g}=\frac{\exp(\delta_j/(1-\sigma_g))}{D_g} \\
\end{align*}

To find the own price elasticities, we will take the derivative of our product shares w.r.t. the products price. We can use the quotient rule to calculate the derivative:

\begin{align*}
\frac{\partial s_{j}}{\partial p_{j}} &= (D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g)^{-2} \bigg(\exp(\frac{\delta_j}{(1-\sigma_g)})(\frac{-\alpha}{(1-\sigma_g)})(D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g) - \dots\\
\dots &-\exp(\frac{\delta_j}{(1-\sigma_g)})\bigg(D_g^\sigma\sum^G_{g=0}((1-\sigma_g)D_g^{-\sigma}\exp(\frac{\delta_j}{(1-\sigma_g)})(\frac{-\alpha}{(1-\sigma_g)}))+\sigma D_g^{\sigma-1}\exp(\frac{\delta_j}{(1-\sigma_g)})(\frac{-\alpha}{(1-\sigma_g)})\sum^G_{g=0}D^{(1-\sigma_g)}_g\bigg)\bigg)\\
&=-\frac{\alpha s_j}{(1-\sigma_g)} (D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g)^{-1}\bigg((D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g) \dots \\ \dots& -(1-\sigma_g)D_g^\sigma\sum^G_{g=0}D_g^{-\sigma}(\exp(\frac{\delta_j}{(1-\sigma_g)})) - \sigma D_g^{\sigma-1}\exp(\frac{\delta_j}{(1-\sigma_g)})\sum^G_{g=0}D^{(1-\sigma_g)}_g\bigg)\\
&=-\frac{\alpha s_j}{(1-\sigma_g)}\bigg(1 -(1-\sigma_g)s_j -  \frac{\sigma D_g^{\sigma}s_{j|g}\sum^G_{g=0}D^{(1-\sigma_g)}_g}{(D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g)}\bigg) )\\
&=-\frac{\alpha s_j}{(1-\sigma_g)}(1 -(1-\sigma_g)s_j -  \sigma s_{j|g})\\
\end{align*}

From this we can calculate our own price elasticities:

\begin{align*}
\frac{\partial q_j}{\partial p_j} \frac{p_j}{q_j}&= L\frac{\partial s_j}{\partial p_j} \frac{p_j}{q_j}\\
&= L(-\frac{\alpha s_j}{(1-\sigma_g)}(1 -(1-\sigma_g)s_j -  \sigma s_{j|g}) ) \frac{p_j}{q_j}\\
&= L(-\frac{\alpha}{(1-\sigma_g)}\frac{q_j}{L}(1 -(1-\sigma_g)s_j -  \sigma s_{j|g}) ) \frac{p_j}{q_j}\\
&=-\frac{\alpha}{(1-\sigma_g)}(1 -(1-\sigma_g)s_j -  \sigma s_{j|g}))p_j\\
\end{align*}

If product k falls within the same segment as j, then we can calculate $\frac{\partial s_k}{\partial p_j}$ as:

\begin{align*}
\frac{\partial s_{k}}{\partial p_{j}} &= - \exp(\frac{\delta_k}{(1-\sigma_g)})(D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g)^{-2}\dots\\
&\dots\bigg(D_g^\sigma\sum^G_{g=0}((1-\sigma_g)D_g^{-\sigma}\exp(\frac{\delta_k}{(1-\sigma_g)})(\frac{-\alpha}{(1-\sigma_g)}))+\sigma D_g^{\sigma-1}\exp(\frac{\delta_k}{(1-\sigma_g)})(\frac{-\alpha}{(1-\sigma_g)})\sum^G_{g=0}D^{(1-\sigma_g)}_g\bigg)\bigg)\\
&=\frac{\alpha s_k}{1-\sigma_g} (D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g)^{-1}\bigg((1-\sigma_g)D_g^\sigma\sum^G_{g=0}(D_g^{-\sigma}\exp(\frac{\delta_k}{(1-\sigma_g)})+\sigma D_g^{\sigma-1}\exp(\frac{\delta_k}{(1-\sigma_g)})\sum^G_{g=0}D^{(1-\sigma_g)}_g\bigg)\bigg)\\
\frac{\partial s_{k}}{\partial p_{j}}&=\frac{\alpha s_k}{1-\sigma_g} ((1-\sigma_g)s_k+\sigma s_{k|g})\\
\end{align*}

From this we can calculate our cross price elasticities for products that are in the same segement:

\begin{align*}
\frac{\partial q_k}{\partial p_j} \frac{p_j}{q_k}&= L\frac{\partial s_k}{\partial p_j} \frac{p_j}{q_k}\\
&= L(\frac{\alpha s_k}{1-\sigma_g} ((1-\sigma_g)s_k+\sigma_g s_{k|g}) ) \frac{p_j}{q_k}\\
&= (\frac{\alpha}{1-\sigma_g}((1-\sigma_g)s_k+\sigma_g s_{k|g}))p_j\\
\end{align*}

If product k falls outside the segment is in j, then we can calculate $\frac{\partial s_k}{\partial p_j}$ as:

\begin{align*}
\frac{\partial s_{k}}{\partial p_{j}} &= - \exp(\frac{\delta_k}{(1-\sigma_g)})(D_g^\sigma\sum^G_{g=0}D^{(1-\sigma_g)}_g)^{-2}\bigg(D_g^\sigma\sum^G_{g=0}((1-\sigma_g)D_g^{-\sigma}\exp(\frac{\delta_k}{(1-\sigma_g)})(\frac{-\alpha}{(1-\sigma_g)}))\bigg)\\
&= \alpha s_k s_j\\
\end{align*}

From this we can calculate our cross price elasticities for products that are outside of segments:

\begin{align*}
\frac{\partial q_k}{\partial p_j} \frac{p_j}{q_k}&= L\frac{\partial s_k}{\partial p_j} \frac{p_j}{q_k}\\
&= L(\alpha s_k s_j) \frac{p_j}{q_k}\\
&= \alpha s_j p_j\\
\end{align*}

4. Estimate the logit model using OLS and 2SLS 

```{}
foreach inst in `characteristics'{;
  2.         qui{;
  3.                 egen is_`inst'=sum(`inst'),  by (year country segment);
  4.                 egen ifs_`inst'=sum(`inst'), by (year country segment firm);
  5.                 gen CFis_`inst'=is_`inst'-ifs_`inst';
  6.                 replace is_`inst'=is_`inst'-`inst';
  7.                 replace ifs_`inst'=ifs_`inst'-`inst';
  8.         };
  9. };

egen seg_sales=sum(qu), by(year country segment);
egen is_num=count(qu), by(year country segment);
egen fs_sales=sum(qu), by(year country segment firm);
egen ifs_num=count (qu), by(year country segment firm);
qui gen CFis_num=is_num-ifs_num;
replace is_num=is_num-1;
gen lnis_num=ln(is_num);
replace ifs_num=ifs_num-1;
gen lnifs_num=ln(ifs_num);
gen sigma=ln(qu/seg_sales);
```

```{}
xtreg rewr price sigma horsepower fuel width height domestic year country2-country5, fe;

Fixed-effects (within) regression               Number of obs      =     11483
Group variable: co                              Number of groups   =       351

R-sq:  within  = 0.8796                         Obs per group: min =         1
       between = 0.7876                                        avg =      32.7
       overall = 0.8453                                        max =       146

                                                F(12,11120)        =   6767.52
corr(u_i, Xb)  = 0.0199                         Prob > F           =    0.0000

------------------------------------------------------------------------------
        rewr |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       price |  -.0491036   .0013895   -35.34   0.000    -.0518273   -.0463799
       sigma |   .8677908    .004327   200.55   0.000     .8593091    .8762725
  horsepower |   .0031765   .0006332     5.02   0.000     .0019354    .0044176
        fuel |  -.0255906   .0048552    -5.27   0.000    -.0351077   -.0160735
       width |   .0112444   .0017935     6.27   0.000     .0077288      .01476
      height |   .0012653   .0023704     0.53   0.593    -.0033811    .0059118
    domestic |   .3883771   .0127901    30.37   0.000     .3633063    .4134479
        year |  -.0025221    .001281    -1.97   0.049    -.0050331   -.0000111
    country2 |  -.3304413   .0120622   -27.39   0.000    -.3540853   -.3067972
    country3 |  -.2093509   .0120898   -17.32   0.000    -.2330489   -.1856528
    country4 |  -.4288399   .0126037   -34.02   0.000    -.4535454   -.4041344
    country5 |   -.104273   .0158302    -6.59   0.000     -.135303    -.073243
       _cons |  -.0712408   2.393163    -0.03   0.976    -4.762264    4.619783
-------------+----------------------------------------------------------------
     sigma_u |  .48769407
     sigma_e |  .38909072
         rho |   .6110556   (fraction of variance due to u_i)
------------------------------------------------------------------------------
F test that all u_i=0:     F(350, 11120) =    19.01          Prob > F = 0.0000

xtivreg rewr (price sigma= i_horsepower i_fuel i_width i_height i_domestic
>                          if_horsepower if_fuel if_width if_height if_domestic
>                          is_horsepower is_fuel is_width is_height is_domestic
>                         ifs_horsepower ifs_fuel ifs_width ifs_height ifs_domestic)
>                         horsepower fuel width height domestic year country2-country5, fe;

Fixed-effects (within) IV regression         Number of obs      =        11483
Group variable: co                           Number of groups   =          351

R-sq:  within  = 0.6001                      Obs per group: min =            1
       between = 0.3725                                     avg =         32.7
       overall = 0.5520                                     max =          146

                                             Wald chi2(12)      =     1.21e+06
corr(u_i, Xb)  = 0.0068                      Prob > chi2        =       0.0000

------------------------------------------------------------------------------
        rewr |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       price |  -.1232378   .0109746   -11.23   0.000    -.1447476    -.101728
       sigma |   .2110286   .0293953     7.18   0.000     .1534147    .2686424
  horsepower |   .0044865    .002236     2.01   0.045     .0001041    .0088689
        fuel |  -.0541376   .0089089    -6.08   0.000    -.0715987   -.0366766
       width |   .0551482   .0036227    15.22   0.000     .0480478    .0622486
      height |   .0255373   .0044086     5.79   0.000     .0168965    .0341781
    domestic |   1.469756   .0545059    26.97   0.000     1.362926    1.576585
        year |  -.0491546   .0031366   -15.67   0.000    -.0553022   -.0430071
    country2 |  -.7585582   .0326599   -23.23   0.000    -.8225704   -.6945461
    country3 |  -.7591188   .0294356   -25.79   0.000    -.8168116    -.701426
    country4 |  -.5304193   .0382404   -13.87   0.000    -.6053692   -.4554694
    country5 |    .142352   .0919044     1.55   0.121    -.0377774    .3224814
       _cons |   80.93904   5.890503    13.74   0.000     69.39387    92.48422
-------------+----------------------------------------------------------------
     sigma_u |  .88552239
     sigma_e |  .70896758
         rho |  .60938692   (fraction of variance due to u_i)
------------------------------------------------------------------------------
F  test that all u_i=0:     F(350,11120) =     7.38       Prob > F    = 0.0000
------------------------------------------------------------------------------
Instrumented:   price sigma
Instruments:    horsepower fuel width height domestic year country2 country3
                country4 country5 i_horsepower i_fuel i_width i_height
                i_domestic if_horsepower if_fuel if_width if_height
                if_domestic is_horsepower is_fuel is_width is_height
                is_domestic ifs_horsepower ifs_fuel ifs_width ifs_height
                ifs_domestic
------------------------------------------------------------------------------
```

The coefficent on prices is now $\alpha=.1232378$ and we have estimated $\sigma_g = .2110286$ (conditional market conditions). Note that the coefficient alpha is negative but our regression assumes there is a negative in front of alpha. Hence alpha itself will be positive according to our formulas. We can see that when instruments are used, our coefficients descrease by a large number relative to original values. Specifically, price coefficients doubles in the negative direction and our $\sigma_g$ falls signfificantly. Without instruments, the model is approaching a logit model as $\sigma_g$ is much closer to 1 then when instruments are used. We can input these values with the known values for shares to find our own- and cross-price elasticities.

5.

For own-price elasticities, we need to calculate $s_g$ to find share of each segment by country and year. We then input our estimated values of $\alpha$ and $\sigma_g$. 

```{}
gen alp = 0.1232378 
gen sigma = 0.2110286
gen sj = qu/MSIZE
egen ig=sum(qu), by(year country segment)
gen sg = ig/MSIZE
gen sjg= sj/sg

gen op = (-alp)/(1-sigma)*(1-(1-sigma)*sj-sigma*sjg)*price

sum op

    Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
          op |     11483   -2.841739    1.363481  -23.39034    -.80102

```

For cross-price elasticities where product k is within the segment:

```{}
gen alp = 0.1232378 
gen sigma = 0.2110286
gen sj = qu/MSIZE

egen ig=sum(qu), by(year country segment)
gen sk=(ig-qu)/MSIZE

gen sg = ig/MSIZE
gen skg= sk/sg

gen op = ((alp)/(1-sigma))*((1-sigma)*sk+sigma*skg)*price

sum op

    Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
          op |     11483    .6190204    .2726837          0   4.891339

```

For cross-price elasticities where product k is outside of the segment:

```{}
gen alp = 0.1232378 
gen sigma = 0.2110286
gen sj = qu/MSIZE
gen op = alp*sj*price

sum op

    Variable |       Obs        Mean    Std. Dev.       Min        Max
-------------+--------------------------------------------------------
          op |     11483    .0031517    .0046634   .0000172   .0432432


```

We can see that the price elasticity within a segement is much higher then outside of the segment. Intuitively this makes sense as sales will be more sensitive to price changes to similar segment of cars instead of prices changes to other segments.

## 3 Merger Simulation 

Estimating a merger between Volkswagen (VW) and Ford in Germany 1998

Logit Specification  w/ endogeneity taken into account.  Note that firm variable = 5 for ford and 26 for VW. Similarly country = 3 for Germany. We are running this code after Q2 and have already generated instruments for logit and Nested logit. 

Logit Specification:

```{}

quietly mergersim init,  price(price) quantity(qu) marketsize(MSIZE) firm(firm);

quietly xtivreg M_ls (price = 	i_horsepower i_fuel i_width i_height i_domestic i_num if_horsepower if_fuel if_width if_height if_domestic i_num) horsepower fuel width height domestic year country2-country5, fe;

 mergersim market if year == 1998;
---------------------------------------------------------------------------------
Supply: Bertrand competition
Demand: Unit demand unnested logit
--------------------------------------------------------------------------------
Demand estimate
xtivreg M_ls (price =   i_horsepower i_fuel i_width i_height i_domestic i_num if_horsepower if_fuel if_width if_heig
> ht if_domestic i_num) horsepower fuel width height domestic year country2-country5, fe
Dependent variable: M_ls
--------------------------------------------------------------------------------

Parameters

alpha = -0.101
----------------------------------------------------------------
Own- and Cross-Price Elasticities:  unweighted market averages

    variable |      mean        sd       min       max
-------------+----------------------------------------
       M_ejj |    -1.686     0.836    -6.328    -0.629
       M_ejk |     0.002     0.003     0.000     0.023
------------------------------------------------------
Observations: 449
----------------------------------------------------------------

Pre-merger Market Conditions 
Unweighted averages by firm

---------------------------------------------------------------------------------
           firm code |              price      Marginal costs   Pre-merger Lerner
---------------------+-----------------------------------------------------------
                 BMW |             20.194              10.166               0.573
                Fiat |             15.277               5.136               0.804
                Ford |             14.557               4.462               0.789
               Honda |             20.094              10.132               0.595
             Hyundai |             12.915               2.959               0.862
                 Kia |             10.814               0.867               1.010
               Mazda |             14.651               4.687               0.746
            Mercedes |             25.598              15.587               0.462
          Mitsubishi |             15.955               5.993               0.679
              Nissan |             15.438               5.452               0.737
                  GM |             21.054              10.939               0.561
                 PSA |             16.243               6.117               0.725
             Renault |             15.518               5.404               0.753
              Suzuki |              9.289              -0.662               1.128
              Toyota |             14.560               4.571               0.808
                  VW |             18.990               8.791               0.705
               Volvo |             23.167              13.202               0.441
              Daewoo |             13.871               3.912               0.814
---------------------------------------------------------------------------------
Variables generated: M_costs M_delta 
---------------------------------------------------------------------------------

. mergersim simulate if year == 1998 & country == 3, seller(5) buyer(26) detail;

---------------------------------------------------------------------------------
Merger Simulation

                                            Simulation method: Newton
                        Buyer     Seller    Periods/markets: 1
Firm                    26        5         Number of iterations: 4
Marginal cost savings                       Max price change in last it: .000044  
---------------------------------------------------------------------------------

Prices
Unweighted averages by firm

---------------------------------------------------------------------------------
           firm code |         Pre-merger         Post-merger     Relative change
---------------------+-----------------------------------------------------------
                 BMW |             17.946              17.946               0.000
                Fiat |             15.338              15.338               0.000
                Ford |             13.093              13.571               0.040
               Honda |             15.778              15.778               0.000
             Hyundai |             12.912              12.912               0.000
                 Kia |             11.276              11.276               0.000
               Mazda |             14.229              14.229               0.000
            Mercedes |             20.114              20.115               0.000
          Mitsubishi |             15.832              15.832               0.000
              Nissan |             15.101              15.101               0.000
                  GM |             19.921              19.921               0.000
                 PSA |             16.397              16.397               0.000
             Renault |             15.292              15.292               0.000
              Suzuki |              9.225               9.225               0.000
              Toyota |             13.019              13.019               0.000
                  VW |             17.182              17.329               0.011
               Volvo |             22.149              22.149               0.000
              Daewoo |             13.483              13.483               0.000
---------------------------------------------------------------------------------
Variables generated: M_price2 M_quantity2 M_price_ch (Other M_ variables dropped)
---------------------------------------------------------------------------------

Market shares by quantity
Unweighted averages by firm

---------------------------------------------------------------------------------
           firm code |         Pre-merger         Post-merger          Difference
---------------------+-----------------------------------------------------------
                 BMW |              0.074               0.075               0.001
                Fiat |              0.043               0.043               0.000
                Ford |              0.095               0.092              -0.004
               Honda |              0.012               0.012               0.000
             Hyundai |              0.006               0.006               0.000
                 Kia |              0.003               0.003               0.000
               Mazda |              0.025               0.025               0.000
            Mercedes |              0.100               0.100               0.001
          Mitsubishi |              0.015               0.015               0.000
              Nissan |              0.025               0.026               0.000
                  GM |              0.166               0.168               0.001
                 PSA |              0.034               0.035               0.000
             Renault |              0.051               0.051               0.000
              Suzuki |              0.006               0.006               0.000
              Toyota |              0.027               0.027               0.000
                  VW |              0.300               0.298              -0.002
               Volvo |              0.012               0.012               0.000
              Daewoo |              0.006               0.006               0.000
---------------------------------------------------------------------------------

--------------------------------------------------
                        Pre-merger     Post-merger
--------------------------------------------------
HHS:                     1501           2038
C4:                     66.07          73.22
C8:                     86.21          88.79
--------------------------------------------------
----------------------------------------
                                 Change
----------------------------------------
Consumer surplus:              -277,498
Producer surplus:                30,470
----------------------------------------

```

*Nested Logit Specification *

```{}
#delimit ;
quietly mergersim init, nests(segment) price(price) quantity(qu) marketsize(MSIZE) firm(firm);

quietly xtivreg M_ls (price M_lsjg= i_horsepower i_fuel i_width i_height i_domestic
			if_horsepower if_fuel if_width if_height if_domestic
			is_horsepower is_fuel is_width is_height is_domestic
			ifs_horsepower ifs_fuel ifs_width ifs_height ifs_domestic)
			horsepower fuel width height domestic year country2-country5, fe;
			
  mergersim market if year == 1998;
---------------------------------------------------------------------------------
Supply: Bertrand competition
Demand: Unit demand one-level nested logit
--------------------------------------------------------------------------------
Demand estimate
xtivreg M_ls (price M_lsjg= i_horsepower i_fuel i_width i_height i_domestic                                                      if_horsepower if_fuel if_width if_height if_domestic                                                 is_horsepower is_fuel is_width is_height is_domestic                                                ifs_horsepower ifs_fuel ifs_width ifs_height ifs_domestic)                                          horsepower fuel width height domestic year country2-country5, fe
Dependent variable: M_ls
--------------------------------------------------------------------------------

Parameters

alpha = -0.123
sigma1 = 0.211 
----------------------------------------------------------------
Own- and Cross-Price Elasticities:  unweighted market averages

    variable |      mean        sd       min       max
-------------+----------------------------------------
       M_ejj |    -2.584     1.272    -9.798    -0.975
       M_ejk |     0.039     0.066     0.000     0.417
       M_ejl |     0.003     0.004     0.000     0.028
------------------------------------------------------
Observations: 449
----------------------------------------------------------------

Pre-merger Market Conditions 
Unweighted averages by firm

---------------------------------------------------------------------------------
           firm code |              price      Marginal costs   Pre-merger Lerner
---------------------+-----------------------------------------------------------
                 BMW |             20.194              13.474               0.381
                Fiat |             15.277               8.562               0.534
                Ford |             14.557               7.910               0.520
               Honda |             20.094              13.638               0.385
             Hyundai |             12.915               6.492               0.556
                 Kia |             10.814               4.407               0.650
               Mazda |             14.651               8.217               0.481
            Mercedes |             25.598              18.497               0.320
          Mitsubishi |             15.955               9.503               0.439
              Nissan |             15.438               8.972               0.477
                  GM |             21.054              14.413               0.368
                 PSA |             16.243               9.528               0.481
             Renault |             15.518               8.839               0.499
              Suzuki |              9.289               2.870               0.728
              Toyota |             14.560               8.093               0.523
                  VW |             18.990              12.197               0.470
               Volvo |             23.167              16.676               0.287
              Daewoo |             13.871               7.440               0.526
---------------------------------------------------------------------------------
Variables generated: M_costs M_delta 
---------------------------------------------------------------------------------

.  mergersim simulate if year == 1998 & country == 3, seller(5) buyer(26) detail;

---------------------------------------------------------------------------------
Merger Simulation

                                            Simulation method: Newton
                        Buyer     Seller    Periods/markets: 1
Firm                    26        5         Number of iterations: 5
Marginal cost savings                       Max price change in last it: 2.7e-07  
---------------------------------------------------------------------------------

Prices
Unweighted averages by firm

---------------------------------------------------------------------------------
           firm code |         Pre-merger         Post-merger     Relative change
---------------------+-----------------------------------------------------------
                 BMW |             17.946              17.947               0.000
                Fiat |             15.338              15.340               0.000
                Ford |             13.093              13.830               0.058
               Honda |             15.778              15.779               0.000
             Hyundai |             12.912              12.912               0.000
                 Kia |             11.276              11.276               0.000
               Mazda |             14.229              14.230               0.000
            Mercedes |             20.114              20.116               0.000
          Mitsubishi |             15.832              15.834               0.000
              Nissan |             15.101              15.102               0.000
                  GM |             19.921              19.926               0.000
                 PSA |             16.397              16.399               0.000
             Renault |             15.292              15.295               0.000
              Suzuki |              9.225               9.225               0.000
              Toyota |             13.019              13.020               0.000
                  VW |             17.182              17.427               0.020
               Volvo |             22.149              22.150               0.000
              Daewoo |             13.483              13.484               0.000
---------------------------------------------------------------------------------
Variables generated: M_price2 M_quantity2 M_price_ch (Other M_ variables dropped)
---------------------------------------------------------------------------------

Market shares by quantity
Unweighted averages by firm

---------------------------------------------------------------------------------
           firm code |         Pre-merger         Post-merger          Difference
---------------------+-----------------------------------------------------------
                 BMW |              0.074               0.075               0.001
                Fiat |              0.043               0.044               0.001
                Ford |              0.095               0.087              -0.009
               Honda |              0.012               0.012               0.000
             Hyundai |              0.006               0.006               0.000
                 Kia |              0.003               0.003               0.000
               Mazda |              0.025               0.026               0.001
            Mercedes |              0.100               0.101               0.002
          Mitsubishi |              0.015               0.016               0.000
              Nissan |              0.025               0.026               0.001
                  GM |              0.166               0.170               0.004
                 PSA |              0.034               0.035               0.001
             Renault |              0.051               0.052               0.001
              Suzuki |              0.006               0.006               0.000
              Toyota |              0.027               0.027               0.001
                  VW |              0.300               0.296              -0.004
               Volvo |              0.012               0.013               0.000
              Daewoo |              0.006               0.006               0.000
---------------------------------------------------------------------------------

--------------------------------------------------
                        Pre-merger     Post-merger
--------------------------------------------------
HHS:                     1501           1995
C4:                     66.07          72.86
C8:                     86.21          88.64
--------------------------------------------------
----------------------------------------
                                 Change
----------------------------------------
Consumer surplus:              -430,685
Producer surplus:               102,669
----------------------------------------
```

2. Report the effect of the merger on prices and consumer welfare in each demand model. 

Merger effect on prices: 

	Logit: Ford: 4% increase , VW: 1.1% increase 
	Nested Logit: Ford: 5.8% increase , VW: 2% increase

Merger effect on consumer welfare:
	
	Logit: decrease of 277,498$
	Nested Logit: decrease of 430,685$

3. Comment on the differences between the results delivered under each demand model. 

As we can see the logit produces smaller estimates for price changes than the nested logit which inturn results in a smaller reduction 
in consumer surplus incomparison to the nested logit. 

The reason driving this difference in the substitution effects and how they differ in the logit and the nested logit. By imposing independence of 
$\epsilon_{ijt}$ across all product it results in unrealistic substitution estimates in the logit model. In the Nested Logit the error 
term is imposed within a segment it allows for correlation in tastes within a segment. In this merger example this means that the 
increase in price of products of a firm within a segment would be recaptured by the other products that the firm has in that segment. 

For example in Germany 1988 volkswagen golf and the ford escort were both compact cars. The nested logit takes in to account the 
fact that some of the reduced quantity of sales as a result of a VW Golf price increase would be recaptured by the sales in ford
escort. This would result in the firms being more willing to raise prices and thus result in a reduction in Consumer surplus. This 
dynamic of within segment substitution is not captured by the standard logit. 
 

# 4.1 Logit Estimation 

Model:

\begin{align*}
u_{ijt} = \beta_0 + \beta^f f_{jt} + \beta^d d_{jt} + \alpha p_{jt} + \xi_{jt} + \epsilon_{ijt}
\end{align*}

constant: vector of ones,

f: amount of caffeine 

d: degrees of roasting

Zopt : Instrument Matrix 

shares: Market Share 

Estimating OLS and 2SLS model in MATlab 

```{}

%BLP ESTIMATOR WITH SIMULATED DATA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 1. Give the Structure of the Data 
%SET GLOBALs
clear;
clear global all;
global ns n cdid cdindex v x2 sj bet W Z x1 nmkt nbrn

% INITIAL SETTING COFFEE DATA
load data
ns          = 100;                          % number of simulated "indviduals" per market 
nmkt        = 25;                           % number of markets = (# of cities)*(# of quarters)  
nbrn        = 10;                           % number of brands per market
n=nmkt*nbrn;  % number of observations    
cdid        = kron((1:nmkt)',ones(nbrn,1)); % vector with marketnumber for each obs
cdindex     = (nbrn:nbrn:nbrn*nmkt)';       % vector with last obs per market 4-8-12
dummarket   = dummyvar(cdid);               % dummies for each market

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 2. Define Matrix Structures for the Estimation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Definitions of matrices%
x1 = [constant p f d];    % x1 matrix for the linear part
x2 = [f];                   % x2 matrix for the nonlinear part  
X = x1;

% Shares
sj      = shares;
sumsj   = dummarket'* sj;               %outside good
sumsj   = sumsj(cdid,:);
s0      = 1 - sumsj;
y       =  log(sj) - log(s0);

Z= instrument

BOLS = inv(X.'*X)*X.'*y
B2SLS = inv(X.'*Z*inv(Z.'*Z)*Z.'*X)*X.'*Z*inv(Z.'*Z)*Z.'*y
 u         = y-X*B2SLS;
dgf         = (250-4);
ser         = (u'*u)./dgf;
sst         = (X'*X)\eye(size(X,2));
sterrLogit  = sqrt(ser*diag(sst));

Results of Logit
    'var'         'OLS'        '2SLS'       'st.err.'
    'constant'    [ 0.4593]    [ 1.7797]    [ 0.5191]
    'price'       [-1.7586]    [-1.9592]    [ 0.0334]
    'char1'       [ 3.0454]    [ 3.1826]    [ 0.2244]
    'char2'       [ 0.8432]    [ 0.9524]    [ 0.2306]
```

Not surprisingly the coefficient on price decreases from -1.7586 to -1.9592 suggesting that the OLS coefficient was biased 
towards zero.  The constant similarly increases in 2SLS, as well as the coefficient associated with the two characsteristics of the coffee brands ( amount of caffeine, and degree of roasting of the beans).  

 

# 4.2 Random Coefficients Logit (BLP)

1. Estimate using Zopt and interpret the ration between the mean and the standard deviation paramters obtained in estimation. Compare with Logit estimates.

```{}
%% Random Coefficients Logit

%Starting Values
rc_sigma0 = 0;      % Gives initial guess for sigma's  
deltastart = ones(n,1);   % Gives initial guess for delta

% rc_sigma0   = 0;                        % Gives initial guess for sigma's  
% deltastart  = y;                        % Gives initial guess for delta from Logit
oldsigma    = zeros(size(rc_sigma0));   % Zero out old theta2
save mvalold deltastart oldsigma        % saves deltastart and oldsigma in mvalold
clear deltastart oldsigma

%OPTIMIZATION
% First define options for optimization
options = optimset('Display','iter-detailed','TolX',1e-6,'TolFun',1e-6);
tic;  %Starts a timer
[rc_sigma,fval,exitflag,output]=fminsearch(@objective,rc_sigma0,options);
timetorun=toc/60;     %Stops the timer and gives minutes to compute

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 4. Standard Errors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Computing the Standard Errors
load mvalold                            % get estimated delta and sigma
beth   = [bet;rc_sigma];                % vector of all parameters
load xi                                 % get the residuals obtained in function objective
derdel  = numgrad('delta',rc_sigma);    % Computes the derivative of delta wrt sigma
a       = [-x1 derdel]'*Z;
dgf     = (size(X,1)-size(X,2));
varcov  = (xi'*xi/dgf)*inv(a*W*a');
stheta  = sqrt(diag(varcov));
ttheta  = beth./stheta;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 5. Reporting Results
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
vars = {'constant', 'price', 'char1', 'char2','sigmachar1'};
title={'var','coef','std.err.','tvalue'};
results=[beth stheta ttheta];
disp('Result of Random Coefficient Logit')
disp([title;vars.',num2cell(results)])

Optimization terminated:
 the current x satisfies the termination criteria using OPTIONS.TolX of 1.000000e-06 
 and F(X) satisfies the convergence criteria using OPTIONS.TolFun of 1.000000e-06 

# of iterations for delta convergence:  1
# of iterations for delta convergence:  15
Result of Random Coefficient Logit
    'var'           'coef'       'std.err.'    'tvalue'  
    'constant'      [ 2.6263]    [  0.5650]    [  4.6486]
    'price'         [-1.9774]    [  0.0401]    [-49.3514]
    'char1'         [ 2.2058]    [  0.3225]    [  6.8401]
    'char2'         [ 0.9889]    [  0.2285]    [  4.3273]
    'sigmachar1'    [-0.9160]    [  0.1311]    [ -6.9849]
```

Interpretting the ratio between the mean and the standard deviation parameters. Since all the coefficients in the model are lognormal distributed than the log of the coefficient are normally distributed. Following the procedure in Train's Discrete Choice Methods with Simulation we can derive estimates of mean, median and variance of the log coefficients. 

The log Coeffiecnets are as follows 
0.96557601
0.68178285
0.79109025
-0.01116206 
-0.08773891

The standard erros 
0.5650, 
0.0401,
0.3225,
0.2285, 
0.1311

mean = exp(logcoef + s/2)
3.4836340
2.0174470 
2.5917680
1.1085889 
0.9780554

Variance = exp(2m + s) [exp(s)  1].
9.2164351 
0.1665273 
2.5564209 
0.3154930
0.1340012

2. Start by drawing 10 invdividuals, than 50 and than 100.


Results with 10 draws 

```{}
# of iterations for delta convergence:  1
# of iterations for delta convergence:  18
Result of Random Coefficient Logit
    'var'           'coef'       'std.err.'    'tvalue'  
    'constant'      [ 2.6810]    [  0.6540]    [  4.0992]
    'price'         [-1.9808]    [  0.0466]    [-42.5372]
    'char1'         [ 1.9077]    [  0.4342]    [  4.3936]
    'char2'         [ 0.9549]    [  0.2648]    [  3.6067]
    'sigmachar1'    [ 1.3902]    [  0.2849]    [  4.8790]
```

Results with 50 draws 

```{}
# of iterations for delta convergence:  1
# of iterations for delta convergence:  12
Result of Random Coefficient Logit
    'var'           'coef'       'std.err.'    'tvalue'  
    'constant'      [ 2.6029]    [  0.5835]    [  4.4607]
    3.
    'price'         [-1.9815]    [  0.0408]    [-48.5259]
    'char1'         [ 2.3482]    [  0.3197]    [  7.3458]
    'char2'         [ 0.8895]    [  0.2338]    [  3.8048]
    'sigmachar1'    [ 0.9038]    [  0.1400]    [  6.4537]
```

Results with 100 draws

```{}
# of iterations for delta convergence:  1
# of iterations for delta convergence:  15
Result of Random Coefficient Logit
    'var'           'coef'       'std.err.'    'tvalue'  
    'constant'      [ 2.6263]    [  0.5650]    [  4.6486]
    'price'         [-1.9774]    [  0.0401]    [-49.3514]
    'char1'         [ 2.2058]    [  0.3225]    [  6.8401]
    'char2'         [ 0.9889]    [  0.2285]    [  4.3273]
    'sigmachar1'    [-0.9160]    [  0.1311]    [ -6.9849]

```

As we can see the coefficient on price when we increase the simulation number of draws from 10,50,100 does not changed drastically hovering around -1.98. The values of sigmachar1 do vary ranging from -0.91 - 1.3902. The coefficient on constant remain similar through all 3 simulations andd the two charactersitics variables vary slightly across the three simulations. The most obvious change between 10 and 100 simulaitons is the value of sigmachar1. 


3. Revisit the logit above and formally show that there is an analytical solution for $\delta_{jt}. Explain why this solution is not possible in a random coefficent model. Describe how contraction mapping works.

Finding an analytical solution for $\delta_{jt}$

From previously since the error is type 1 extreme value that market shares for product j and the outside good are defined as 

\begin{align*}
s_{j} &= \frac{\exp(\delta_j}{1 + \sum^j_k \exp(\delta_k)}\\
s_{0} &= \frac{1}{1 + \sum^j_k \exp(\delta_k)}
\end{align*}

Taking the logs of both of these equations
\begin{align*}
\ln(s_{j}) &= \ln(\frac{\exp(\delta_j}{1 + \sum^j_k \exp(\delta_k)})\\
\ln(s_{j}) &=  \delta_j  - \sum^j_k \delta_k\\
\ln(s_{0}) &= \ln(\frac{1}{1 + \sum^j_k \exp(\delta_k)}) \\
\ln(s_{0}) &= - \sum^j_k \delta_k \\
\end{align*}

Subtracting $\ln(s_j) - \ln(s_0)$
\begin{align*}
\ln(s_{j}) -  \ln(s_{0}) & =  \delta_j  - \sum^j_k \delta_k +  \sum^j_k \delta_k \\
\ln(\frac{s_{j}}{s_{0}}  & =  \delta_j  \\
\end{align*}

Therefore we have an analytic solution for $\delta_j$. 

It is not possible to attain this in the random coeffecients logit because we approximate market shares through a monte carlo simulation. 
Since the equation for marketshares is given by: 

$s_{jt} =\int \frac{\exp(\delta_{jt} + \mu_{ijt}(v))}{1 + \sum^J_k \exp(\delta_{kt} + \mu_{ikt}(v))}dP_v(v)$

This integral grows in complexity the number of random coefficients to not having a closed form analytical solution and instead we approximate through simulation. 

Contraction Mapping:
The approximated market share is given by this equation:

$s_{jt} = (ND)^{-1}\sum^{ND}_i \frac{exp(\delta_{jt} +\sigma_\beta v_\beta x_j )}{1 + \sum^J_k \exp(\delta_{kt} + x_{kt}\sigma_{\beta}v_{it}) }$

At this point both $\sigma$ and $\delta_j$ are unknown. We than for a given $\sigma$ begin with $\delta_j^0$ and solve the marketshare function producing $s_t(\delta_j^0)$. We than compare this value to our observed marketshare to come up with a new value for $\delta_j$ through contract mapping in each market.

$\delta^1_j = \delta^0_j + \ln(s_t) -  \ln(s_t(\delta_j^0))$

We than get $\delta^1_j $ recompute the market shares using this value to get $s_t(\delta_j^1)$ and revisit contract mapping to get $\delta^2_j = \delta^1_j + \ln(s_t) -  \ln(s_t(\delta_j^1))$. This iteration continous until the difference between  $\ln(s_t) -  \ln(s_t(\delta_j)) $ is significantly small with a minimum tolerance of  $10^{-12}$.

Once we have the delta produced by a certain $\sigma$ we use the matrix equation for 2SLS using W as the GMM weight matrix to solve for parameters. $\hat\theta =[\beta , \alpha]$ 

$\hat \theta = (X'ZWZ'X)^{-1}X'ZWZ'\delta(\sigma)$ 

Using $\hat \theta$ we than can recover the econometric error term $\xi$. Using the instruments we than find the \sigma that minimizes this expression.

$\min_{\sigma} \xi' ZWZ'\xi$

If the $\sigma$ that minimizes this expression is the same one we originally guessed in our contract mapping we are finished if not we than use this new estimate of sigma to restart our contract mapping until the $\sigma$ that minimizes the error term interacted with the instruments is the one that we used to generate our estimate of $\delta_j$. 

4. Derive the own price and cross price elasticities in the random coefficient logit model.

Estimating cross-price elasticities = $\frac{\partial s_j}{\partial p_k}$

$s_{jt} =\int \frac{\exp(\delta _jt + \mu _{ijt}(v))}{1 + \sum^J_k \exp(\delta_{kt} + \mu_{ikt}(v))}$

But since we can only approximate market shares through Monte Carlo simulation  x_{kt}\sigma _{\beta}v_{it})

$s_{jt} = (ND)^{-1}\sum^{ND}_i \frac{exp(\delta _jt +\sigma_\beta v_\beta x_j )}{1 + \sum^J_k \exp(\delta_{kt} + x_{kt}\sigma _{\beta}v_{it}) }$


\begin{align*}
frac{\partial s_j}{\partial p_k}  = 
\end{align*}
